### ISSUE TITLE
NL Birthdates with XX

### ISSUE THREAD

**Issue by SchulzeStTSI** [ehn-digital-green-development/ehn-dgc-schema#78]
We received a lot of requests about valid birth dates from NL which can have the format of XX-XX-1963. This one are rejected by the schema. Is there a way to support it?

**Comment by jschlyter** [comment]
Per the latest version of the schema, date of birth MUST be formatted as YYYY-MM-DD, YYYY-MM, or YYYY.

@gabywh, please confirm.

**Comment by gabywh** [comment]
> Per the latest version of the schema, date of birth MUST be formatted as YYYY-MM-DD, YYYY-MM, or YYYY.
> 
> @gabywh, please confirm.

Yes can confirm, v1.1.0 - but do please note the OP:

> valid birth dates from NL which can have the format of XX-XX-1963. 

This is not correct for two main reasons:
1. the "ICAO" format (at least: it is the ICAO Use Case here, so I'll just refer to it as the "ICAO format" for short, so that way we keep both the physical format plus the Use Case in mind) is `1963-XX-XX`
2. this is definitively NOT supported in the DGC schema which is ISO8601

At the risk of repeating myself:
1. ICAO can have e.g. 1963-XX-XX
2. An ISO8601 equivalent would be 1963 (thus: YYYY)

Two Use Cases for comparison:
1. Manual:
  1. 1963-XX-XX (ICAO) says: "there is no month to compare and no day to compare, so you can only compare year"
  2. 1963 (ISO8601) says:  "there is no month to compare and no day to compare, so you can only compare year"
  3. result: a manual comparison compares year only
2. Programmatic:
  1. one line of Python to compare "1963-XX-XX" with "1963"
  
Given that the QR code will be scanned, the programmatic comparison will most likely be used in the verification business rules.

**Comment by gabywh** [comment]
Detailed in: https://github.com/ehn-digital-green-development/ehn-dgc-schema/releases/tag/1.1.0

**Comment by ijansch** [comment]
Although XX-XX-1963 is indeed a dutch birthdate, it's the yyy-mm-dd version of it (1963-XX-XX) what we'd like to put in the date field, as that matches what is on the ID card that a verifier would check against.

**Comment by chris2286266** [comment]
Sorry, but "1963-XX-XX" does NOT conform to the schema and/or ISO8601. I suggest, that you just use "1963" and a) let your local Validation-App display "1963-XX-XX" in such a case and/or b) leave it to the verifier to recognize, that a birthdate displayed as "1963" is the same as "1963-XX-XX".

**Comment by wasperen** [comment]
in the latest version (https://github.com/eu-digital-green-certificates/dgc-testdata/tree/6c4da5873361081362d599ea55fd6c01cd46d017/NL) we have settled on the following example dates:

```
T:2021-01-01
T:1963
T:1964-01
T:1963-00
T:1953-09-03
T:2000-02-29
F:1815-08-24
F:2023-01-01
```

**Comment by wasperen** [comment]
> Sorry, but "1963-XX-XX" does NOT conform to the schema and/or ISO8601. I suggest, that you just use "1963" and a) let your local Validation-App display "1963-XX-XX" in such a case and/or b) leave it to the verifier to recognize, that a birthdate displayed as "1963" is the same as "1963-XX-XX".

that is the decision we have taken. we never had XX-XX-1963, but did have 1963-XX-XX in there, which we now settled on.

**Comment by chris2286266** [comment]
> that is the decision we have taken. we never had XX-XX-1963, but did have 1963-XX-XX in there, which we now settled on.

Whom do you mean by "we"?

**Comment by wasperen** [comment]
> > that is the decision we have taken. we never had XX-XX-1963, but did have 1963-XX-XX in there, which we now settled on.
> 
> Whom do you mean by "we"?

we as in The Netherlands

**Comment by wasperen** [comment]
https://github.com/ehn-digital-green-development/ehn-dgc-schema/releases/tag/1.1.0

this fixes it

**Comment by gabywh** [comment]
> > Sorry, but "1963-XX-XX" does NOT conform to the schema and/or ISO8601. I suggest, that you just use "1963" and a) let your local Validation-App display "1963-XX-XX" in such a case and/or b) leave it to the verifier to recognize, that a birthdate displayed as "1963" is the same as "1963-XX-XX".
> 
> that is the decision we have taken. we never had XX-XX-1963, but did have 1963-XX-XX in there, which we now settled on.

Which is just ridiculous and violates (1) an ISO standard, and (2) the eHealthNetwork guidelines for interoperability. 
I guess any further comment is superfluous

**Comment by wasperen** [comment]
Hey Gabi - as you see here https://github.com/ehn-digital-green-development/ehn-dgc-schema/issues/78#issuecomment-848860527 we are now using completely ISO compliant dates. You will find these in the test cases that we submitted into the testdata repository a couple of days ago and which have subsequently been merged  into the set. Sorry for any confusion. Regards, W

**Comment by vaubaehn** [comment]
> Which is just ridiculous and violates (1) an ISO standard, and (2) the eHealthNetwork guidelines for interoperability.
> I guess any further comment is superfluous

I'm surprised about the communication style among/between collaborators.
